version: '2.1'
services:
  server:
    build: .
    command: npm run start:dev
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - 3000
    container_name: 'server'
  nginx:
    container_name: 'nginx'
    image: 'nginx'
    ports:
      - 3033:80
    volumes:
      - ./src/volumes/conf.d:/etc/nginx/conf.d/default.conf