version: '2.1'
services:
  server:
    build: .
    command: npm run start:dev
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - 3000
    container_name: 'server'
  app:
    build: .
    command: npm run start:dev
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - 3000
    container_name: 'server'